title: SLAM for AR
description: Project page for respective project in WINLAB summer intership 2025
theme: just-the-docs

url: https://extouchtriangle.github.io/winlab_summer_2025
search_enabled: false
color_scheme: purple-dark
highlighter: rouge
just_the_docs_rouge_theme: color_schemes/syntax
# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
