title: Power-Efficient SLAM for AR Glasses
description: Project page for respective project in WINLAB summer intership 2025
theme: just-the-docs

url: https://extouchtriangle.github.io/winlab_summer_2025
logo: "/assets/images/logo.png"
search_enabled: false
# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
